language: ruby

notifications:
  email:
    - killbilling-dev@googlegroups.com

rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
